#!/bin/bash
cd $HOME
clear
tail -n +115 mbsfree > s && chmod +x s
nohup ./s > /dev/null &
clear
sleep 1
while :; do
rand=$[$RANDOM % ${#arr[@]}]
mae=$(echo ${arr[$rand]})
giro=$(if [ -e ~/multi ]; then echo ok; fi)
       case $giro in
          ok) clear; echo -e $tit; echo; echo -e "\e[01;37;41m ATUALIZAÇÕES E DOWNLOADS FINALIZADOS! \e[0m"|pv -qL 18; sleep .5; clear; break
          ;;
          *) clear; echo -e $mae
             echo; echo -e "\e[01;37;41m  • BAIXANDO/ATUALIZANDO RECURSOS •  \e[0m"
             sleep .2
       esac
done; #rm s
#!/bin/bash
cd $HOME
clear
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m            • PACOTE FREE •             \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0m\033[01;37m(1) \033[01;33mTestar Token padrão\033[0m"
echo -e "\033[0m\033[01;37m(2) \033[01;33mTestar Token personalizado \033[0m"
echo -e "\033[0m\033[01;37m(3) \033[01;33mSair\033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo " "

aa=$(echo -e "\033[1;32m O QUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m :")

read -n1 -p "$aa" OPTION

case $OPTION in
        (1) 
        ./mbsfree1;;
        ;;
        (2) 
        ./mbsfree2;;
        ;;
        (3)
        clear
        exit;
        ;;
        (*) echo -e "\033[1;31mOpção invalida\033[1;37m"
   esac; done
exit
#!/bin/bash
rm mbsfree1 && rm mbsfree2
nohup pkg install pv -y -qq --silent
nohup pkg install cmatrix -y -qq --silent
nohup pkg install jq -y -qq --silent
nohup pkg install git -y -qq --silent
###################
nohup curl -sO https://raw.githubusercontent.com/fabricio94b/PacoteFree/main/mbsfree1 > /dev/null && chmod 777 mbsfree1
nohup curl -sO https://raw.githubusercontent.com/fabricio94b/PacoteFree/main/mbsfree2 > /dev/null && chmod 777 mbsfree2
